# Generated by Django 4.2.6 on 2023-10-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_year', models.DateField()),
                ('movie_quality', models.CharField(max_length=2)),
                ('movie_time', models.CharField(max_length=20)),
                ('movie_rating', models.CharField(max_length=10)),
            ],
        ),
    ]
