# Generated by Django 4.2.6 on 2023-10-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_movie_cardtwo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie_cardtwo',
            new_name='movie_vard',
        ),
    ]
