# Generated by Django 4.2.6 on 2023-10-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_delete_movie_vard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_card',
            name='movie_quality',
            field=models.CharField(max_length=3),
        ),
    ]
